[workspace]
members = [
    "apps/serp-derp/src-tauri",
    "crates/*"
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tauri = { version = "2.0.0-beta", features = [] }
thiserror = "1.0" 