packages:
  - 'apps/*'
  - 'packages/*' 

catalog:
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "@types/node": "^20"
  "@types/react": "^19"
  "@types/react-dom": "^19"
  "lucide-react": "^0.503.0"