/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as AnalysisRouteImport } from './routes/analysis/route'
import { Route as IndexImport } from './routes/index'
import { Route as AnalysisIndexImport } from './routes/analysis/index'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const AnalysisRouteRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AnalysisIndexRoute = AnalysisIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalysisRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexImport
      parentRoute: typeof AnalysisRouteImport
    }
  }
}

// Create and export the route tree

interface AnalysisRouteRouteChildren {
  AnalysisIndexRoute: typeof AnalysisIndexRoute
}

const AnalysisRouteRouteChildren: AnalysisRouteRouteChildren = {
  AnalysisIndexRoute: AnalysisIndexRoute,
}

const AnalysisRouteRouteWithChildren = AnalysisRouteRoute._addFileChildren(
  AnalysisRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/analysis/': typeof AnalysisIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/analysis': typeof AnalysisIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/analysis/': typeof AnalysisIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analysis' | '/settings' | '/analysis/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/analysis'
  id: '__root__' | '/' | '/analysis' | '/settings' | '/analysis/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRouteRoute: typeof AnalysisRouteRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRouteRoute: AnalysisRouteRouteWithChildren,
  SettingsRoute: SettingsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/analysis",
        "/settings"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/analysis": {
      "filePath": "analysis/route.tsx",
      "children": [
        "/analysis/"
      ]
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/analysis/": {
      "filePath": "analysis/index.tsx",
      "parent": "/analysis"
    }
  }
}
ROUTE_MANIFEST_END */
