//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::page_rule_result::Entity as PageRuleResult;
pub use super::plugin_rule::Entity as PluginRule;
pub use super::site::Entity as Site;
pub use super::site_page::Entity as SitePage;
pub use super::site_run::Entity as SiteRun;
