//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, specta :: Type,
)]
#[sea_orm(table_name = "site")]
#[specta(rename = "SiteModel")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(unique)]
    pub url: String,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::page_rule_result::Entity")]
    PageRuleResult,
    #[sea_orm(has_many = "super::site_page::Entity")]
    SitePage,
    #[sea_orm(has_many = "super::site_run::Entity")]
    SiteRun,
}

impl Related<super::page_rule_result::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PageRuleResult.def()
    }
}

impl Related<super::site_page::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SitePage.def()
    }
}

impl Related<super::site_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SiteRun.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
