[package]
name = "seo-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
scraper = "0.18.1"
url = "2.5.0"
reqwest = { version = "0.11", features = ["json"] }
tempfile = "3.10.1"
async-trait = "0.1"