name: AppStore Release

# NOTE: Test vals
on:
    push:
      branches:
        - main
    pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
    publish-to-appstore:
        runs-on: macos-latest
        env:
            APPLE_ID: ${{ secrets.APPLE_ID }}
            APPNAME: Serpeo
            APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
            APPLE_API_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
            APPLE_API_ISSUER: ${{ secrets.APPLE_ISSUER_ID }}
        steps:
            - uses: actions/checkout@v4
            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable
              with:
                targets: 'aarch64-apple-darwin,x86_64-apple-darwin'
            
            - uses: ./.github/actions/ci-setup

            - uses: Swatinem/rust-cache@v2
            - name: Import Apple Developer Certificate
              env:
                APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE_DIST }}
                APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD_DIST }}
                KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
              run: |
                echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12
                security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
                security default-keychain -s build.keychain
                security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
                security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
                security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
                security find-identity -v -p codesigning build.keychain
            - name: Verify Certificate
              run: |
                CERT_INFO=$(security find-identity -v -p codesigning build.keychain | grep "Apple Distribution")
                CERT_ID=$(echo "$CERT_INFO" | awk -F'"' '{print $2}')
                echo "CERT_ID=$CERT_ID" >> $GITHUB_ENV
                echo "Certificate imported."
            - name: Setup AppStore Connect API KEY
              run: |
                mkdir private_keys 
                echo $APPLE_KEY_CONTENT | base64 --decode > private_keys/AuthKey\_$APPLE_KEY_ID.p8
                echo "Private key decoded."
            - name: Add Rust target for iOS
              run: |
                rustup target add aarch64-apple-ios
            - name: Build iOS App
              run: |
                pnpm tauri ios build --export-method app-store-connect

            - name: Upload iOS App to AppStore Connect
              working-directory: apps/serpeo
              run: |
                xcrun altool --upload-app --type ios --file "src-tauri/gen/apple/build/arm64/Serpeo.ipa" --apiKey $APPLE_API_KEY_ID --apiIssuer $APPLE_API_ISSUER
                echo "App uploaded to AppStore Connect."

            - name: Build macOS App
              run: |
                pnpm tauri build --bundles app --target universal-apple-darwin
                echo "macOS App built."

            - name: Upload macOS App to AppStore Connect
              run: |
                xcrun productbuild --sign "$CERT_ID" --component "target/universal-apple-darwin/release/bundle/macos/$APPNAME.app" /Applications "$APPNAME.pkg"
                xcrun altool --upload-app --type macos --file "$APPNAME.pkg" --apiKey $APPLE_API_KEY_ID --apiIssuer $APPLE_API_ISSUER
                echo "macOS App uploaded to AppStore Connect."
            