name: Static Check

on:
  push:
    branches:
      - main

  pull_request:
    branches-ignore:
      - changeset-release/main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # - name: Install rust deps
      #   run: sudo apt install libwebkit2gtk-4.1-dev
      - uses: ./.github/actions/rust-setup
      - uses: ./.github/actions/ci-setup
      

      - uses: bnjbvr/cargo-machete@main

      # Running Lint with --quiet to only print errors
      - name: Static Check...
        run: pnpm static
        # env:
        #   NODE_OPTIONS: "--max_old_space_size=8192"

      # - name: Running Static Check...
      #   run: pnpm typecheck
      #   env:
      #     NODE_OPTIONS: "--max_old_space_size=8192"

      - name: Static Check ✅
        if: ${{ success() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "static-check",
            "state": "success",
            "description": "Static Check passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

      - name: Static Check 🚨
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "static-check",
            "state": "failure",
            "description": "Static Check failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
